on:
  push:
    branches:
      - "**"
  pull_request:
  merge_group:

name: Run tests
jobs:
  # The `ci-result` job doesn't actually test anything - it just aggregates the
  # overall build status, otherwise the merge queue would need an entry
  # for each individual job produced by the job-matrix.
  #
  # ALL THE SUBSEQUENT JOBS NEED THEIR `name` ADDED TO THE `needs` SECTION OF both "ci result" JOBS!
  ci-success:
    name: ci result
    runs-on: ubuntu-latest
    needs:
      - lint
      - geo_types
      - geo
      - geo_postgis
      - geo_fuzz
      - bench
      - docs
    if: success()
    steps:
      - name: Mark the job as a success
        run: exit 0
  ci-failure:
    name: ci result
    runs-on: ubuntu-latest
    needs:
      - lint
      - geo_types
      - geo
      - geo_postgis
      - geo_fuzz
      - bench
    if: failure()
    steps:
      - name: Mark the job as a failure
        run: exit 1

  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        container_image:
          # Use the latest stable version. No need for older versions.
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: apt-get update && apt-get install -y libgeos-dev
      - run: rustup component add rustfmt clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets -- -Dwarnings

  geo_types:
    name: geo-types
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        working-directory: geo-types
    strategy:
      matrix:
        container_image:
          # We aim to support rust-stable plus (at least) the prior 3 releases,
          # giving us about 6 months of coverage.
          #
          # Minimum supported rust version (MSRV)
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.81"
          # Two most recent releases - we omit older ones for expedient CI
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.83"
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: rustup target add thumbv7em-none-eabihf
      - run: cargo check --all-targets --no-default-features
      - run: cargo check --lib --target thumbv7em-none-eabihf --no-default-features -F use-rstar_0_9,serde
      - run: cargo test --all-features

  geo:
    name: geo
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        working-directory: geo
    strategy:
      matrix:
        container_image:
          # We aim to support rust-stable plus (at least) the prior 3 releases,
          # giving us about 6 months of coverage.
          #
          # Minimum supported rust version (MSRV)
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.81"
          # Two most recent releases - we omit older ones for expedient CI
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.83"
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cargo check --all-targets --no-default-features
      # we don't want to test `proj-network` because it only enables the `proj` feature
      - run: cargo test --features "use-proj use-serde earcutr multithreading"

  geo-generic:
    name: geo-generic
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        working-directory: geo-generic-alg
    strategy:
      matrix:
        container_image:
          # We aim to support rust-stable plus (at least) the prior 3 releases,
          # giving us about 6 months of coverage.
          #
          # Minimum supported rust version (MSRV)
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.81"
          # Two most recent releases - we omit older ones for expedient CI
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.83"
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: apt-get update && apt-get install -y libgeos-dev
      - run: cargo check --all-targets
      - run: cargo test --lib --bins --tests
      - run: cd ../geo-generic-tests && cargo test

  geo_traits:
    name: geo-traits
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        working-directory: geo-traits
    strategy:
      matrix:
        container_image:
          # We aim to support rust-stable plus (at least) the prior 3 releases,
          # giving us about 6 months of coverage.
          #
          # Minimum supported rust version (MSRV)
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.81"
          # Two most recent releases - we omit older ones for expedient CI
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.83"
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cargo check --all-targets
      - run: cargo test

  geo_postgis:
    name: geo-postgis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        working-directory: geo-postgis
    strategy:
      matrix:
        container_image:
          # We aim to support rust-stable plus (at least) the prior 3 releases,
          # giving us about 6 months of coverage.
          #
          # Minimum supported rust version (MSRV)
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.81"
          # Two most recent releases - we omit older ones for expedient CI
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.83"
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cargo check --all-targets
      - run: cargo test

  geo_fuzz:
    name: geo-fuzz
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    defaults:
      run:
        working-directory: geo/fuzz
    strategy:
      matrix:
        container_image:
          # Fuzz only on latest
          - "ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84"
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cargo build --bins

  bench:
    name: bench
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: apt-get update && apt-get install -y libgeos-dev
      - run: cargo bench --no-run

  docs:
    name: build documentation
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: ghcr.io/georust/geo-ci:proj-9.5.0-rust-1.84
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
